name: C# Application
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches:
        - main
        paths:
        - DevOps/Lab3
        - .github/workflows/*.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore ./DevOps/Lab3/TestApp

      - name: Build project
        run: dotnet build ./DevOps/Lab3/TestApp --configuration Release

      - name: Run tests
        run: dotnet test ./DevOps/Lab3/TestApp --configuration Release

      - name: Deploy application
        run: |
          echo "Application deployed"
