FROM python:latest

WORKDIR /ml

RUN apt-get update

RUN apt-get install -y \
    build-essential \
    curl

RUN apt-get update

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN pip install seaborn
RUN pip install scikit-learn
RUN pip install pandas
RUN pip install numpy
RUN pip install catboost
RUN pip install jupyterlab
RUN pip install notebook

EXPOSE 8888

COPY . /ml

CMD ["jupyter", "notebook", "--allow-root", "--ip=\"0.0.0.0\""]