version: "3"

services:
  database:
    image: mongo
    container_name: ra_database
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ra_db:/data/db
    networks: 
      - backend
  server:
    build: ./server.js
    container_name: ra_server
    depends_on:
      - database
    ports:
      - "8081:8080"
    networks: 
      - backend
      - frontend
  nginx:
    build: ./nginx
    container_name: ra_nginx
    depends_on:
      - server
    ports:
      - "8080:80"
      - "8000:443"
    networks: 
      - frontend

volumes:
  ra_db:
    external: true

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge
