name: C# Application
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches:
        - main
        paths:
        - DevOps/Lab3
jobs:
  built:
    runs-on: ubuntu-22.04
    steps:
        - name: checkout
          uses: actions/checkout@v4
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 8.0.x
  
        - name: Restore dependencies
          run: dotnet restore
  
        - name: Build
          run: dotnet build --no-restore
  
        - name: Test
          run: dotnet test --no-build --verbosity normal