name: C# Application
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches:
        - main
        paths:
        - DevOps/Lab3
        - .github/workflows/goodPractice.yml

env:
  App_Path: ./DevOps/Lab3/TestApp

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $App_Path

      - name: Build project
        run: dotnet build $App_Path --no-restore --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ${{ env.App_Path }}/**/bin/Release/net8.0/

  test:
    runs-on: ubuntu-22.04
    needs: build
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Run tests
        run: dotnet test $App_Path --no-restore --no-build --configuration Release

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Deploy application
        run: |
          echo "Application deployed"
